/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package videoconferencia;

import java.io.DataOutputStream;
import java.io.IOException;
import java.net.ConnectException;
import java.net.InetAddress;
import java.net.Socket;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class interfazCliente extends javax.swing.JFrame {

    /**
     * Creates new form interfazCliente
     */
    public interfazCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        botonIniSesion = new javax.swing.JButton();
        ipLabel = new javax.swing.JLabel();
        registroUsuario = new javax.swing.JTextField();
        tituloConferencia = new javax.swing.JLabel();
        IpTextField = new javax.swing.JTextField();
        nombreUsuario1 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonIniSesion.setBackground(new java.awt.Color(255, 153, 102));
        botonIniSesion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botonIniSesion.setText("Iniciar Sesión");
        botonIniSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIniSesionActionPerformed(evt);
            }
        });

        ipLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ipLabel.setText("Ip del Anfitrion");

        tituloConferencia.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        tituloConferencia.setForeground(new java.awt.Color(51, 51, 255));
        tituloConferencia.setText("Registro a la Video Conferencia");

        nombreUsuario1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nombreUsuario1.setText("Nombre Usuario:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tituloConferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(registroUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(ipLabel)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(botonIniSesion))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(IpTextField)))
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(36, 36, 36)
                    .addComponent(nombreUsuario1)
                    .addContainerGap(131, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(tituloConferencia)
                .addGap(82, 82, 82)
                .addComponent(registroUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(ipLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonIniSesion)
                .addContainerGap(55, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(108, 108, 108)
                    .addComponent(nombreUsuario1)
                    .addContainerGap(149, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonIniSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIniSesionActionPerformed

        // TODO add your handling code here:
        String nombreUsuario = registroUsuario.getText();

        Conexion cc = new Conexion();
        Connection cn = null;
        try {
            cn = cc.getConexion();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(interfazAnfitrion.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            if (existe(nombreUsuario)) {
                JOptionPane.showMessageDialog(null, "EL USUARIO YA EXISTE!!!");
                interfazAnfitrion anfitrion = new interfazAnfitrion();
                anfitrion.setVisible(true);
                this.dispose();
            } else {

                PreparedStatement pst = cn.prepareStatement("INSERT INTO USUARIO(NOMBRE_USUARIO) VALUES(?)");
                pst.setString(1, nombreUsuario);
                int a = pst.executeUpdate();
                if (a > 0) {
                    JOptionPane.showMessageDialog(null, "Registro exitoso");
                    limpiar();
                } else {
                    JOptionPane.showMessageDialog(null, "Error al agregar");
                }
            }
        } catch (Exception e) {
        }

        //conexion con el servidor
        Socket miSocket;
        try {
            //String ip = InetAddress.getLocalHost().getHostAddress();
            //Socket miSocket = new Socket("192.168.100.2",9999); // isra
            //miSocket = new Socket("192.168.0.106", 9999); // da
            /*
            usuario debe conectarse a la ip del servidor
            entonces el servidor debe mostrar su ip
             */

            miSocket = new Socket(IpTextField.getText(), 9999); //general

            DataOutputStream flujo_salida = new DataOutputStream(miSocket.getOutputStream());
            flujo_salida.writeUTF(registroUsuario.getText());
            flujo_salida.close();

        } catch (ConnectException c) {
            JOptionPane.showMessageDialog(null, "Error de conexion. \n " + c.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);

        } catch (IOException ex) {
            Logger.getLogger(interfazCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botonIniSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfazCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfazCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfazCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfazCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfazCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IpTextField;
    private javax.swing.JButton botonIniSesion;
    private javax.swing.JLabel ipLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nombreUsuario1;
    private javax.swing.JTextField registroUsuario;
    private javax.swing.JLabel tituloConferencia;
    // End of variables declaration//GEN-END:variables

    private boolean existe(String nombreUsuario) throws SQLException, ClassNotFoundException {
        PreparedStatement ps = null;
        Conexion cc = new Conexion();
        Connection cn = null;
        cn = cc.getConexion();
        //Connection con = getConexion();
        ResultSet rs;
        String sql = "SELECT NOMBRE_USUARIO FROM USUARIO WHERE NOMBRE_USUARIO = ?";

        ps = cn.prepareStatement(sql);
        ps.setString(1, nombreUsuario);
        rs = ps.executeQuery();

        if (rs.next()) {
            return true;

        } else {
            return false;
        }

    }

    private void limpiar() {
        registroUsuario.setText("");

    }

}
